//$Id$

package net.sf.persist.tests.common;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

@Table(name = "simple")
public class Simple12 {
    private long id;
    private boolean complete;

    @Column(autoGenerated = true)
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }


    public boolean isComplete() {
        return complete;
    }

    public void setComplete(boolean complete) {
        this.complete = complete;
    }
}

