//$Id$

package net.sf.persist.tests.common;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

@Table(name="simple")
public class Simple11 {

    private long id;
    private Color stringCol;
    private long intCol;

    @Column(autoGenerated = true)
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Color getStringCol() {
        return stringCol;
    }

    public void setStringCol(Color stringCol) {
        this.stringCol = stringCol;
    }

    public long getIntCol() {
        return intCol;
    }

    public void setIntCol(long intCol) {
        this.intCol = intCol;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;

        final Simple11 other = (Simple11) obj;

        // do not compare ids -- will be tested in the autogeneratedkeys tests
        // if (id != other.id) return false;

        if (intCol != other.intCol)
            return false;
        if (stringCol == null) {
            if (other.stringCol != null)
                return false;
        } else if (!stringCol.equals(other.stringCol))
            return false;

        return true;
    }

    public String toString() {
        return "id=" + id + " intCol=" + intCol + " stringCol=" + stringCol;
    }
}

